### ISSUE TITLE
I'm not getting local host ip address 127.0.0.1

### ISSUE THREAD

**Issue by sariyu** [pbojinov/request-ip#14] opened 2015-10-20 12:48 UTC
I'm getting "::1" this as my ip address, is this an issue ?

**Comment by pbojinov** [comment] 2015-10-20 18:59
That's not good, i'll take a look.

Can you post some of the code you're using it in and maybe some details about the environment?

**Comment by Belev** [comment] 2015-10-25 17:33
Hello,

I have just tried the library and for localhost I get the following result: ::ffff:127.0.0.1. From what I read in the readme that is not the expected behaviour.

I am using Node v4.2.1 with Express v4. Using the code sample from the readme file but not in middleware. I call getClientIp in my controller.

**Comment by pbojinov** [comment] 2015-10-27 20:01
Another scenario from Martin:

I have just tried the library and for localhost I get the following result: ::ffff:127.0.0.1.

I am using Node v4.2.1 with Express v4. Using the code sample from the readme file but not in middleware.

**Comment by Belev** [comment] 2015-10-27 21:24
I have deleted the comment because that's the case when getting IPv6. I don't know much about ips, but from what I see it depends what kind of IP will be returned - IPv4 or IPv6. So it is expected behaviour in my opinion.
To check the IP type **net** module from the built in modules in node can be used. There are three functions for that - **isIP**, **isIPv4**, **isIPv6**. More information - [click](https://nodejs.org/api/net.html#net_net_isip_input).

**Comment by pbojinov** [comment] 2015-10-27 22:24
@Belev I haven't tested it on IPv6, but that makes sense. Thanks for your info, I'll make a note of it in the README.me about IPv6 and IPv4.

**Comment by pbojinov** [comment] 2016-01-27 21:18
Looks like this is the expected behavior if you have IPv6 enabled. It also all depends on what entries you have in your `/etc/hosts` file.

In this case I tested it locally on my machine using a simple node server with the request-ip connect middleware on OSX 10.11.2 and got the following results:

```
wget http://127.0.0.1:3000 => ::ffff:127.0.0.1
wget http://localhost:3000 => ::1
```

Now the question is should all of those return the IPv4 address of 127.0.0.1 or the current IPv6 responses?

**Comment by pbojinov** [comment] 2016-02-05 19:18
Closing this for now, don't think its an issue. I've added docs in the README explaining the values that will be returned based on your IP version. 

```
// on localhost you'll see 127.0.0.1 if you're using IPv4 
// or ::1, ::ffff:127.0.0.1 if you're using IPv6
```

**Closed by pbojinov** 2016-02-05 19:18 UTC
